### ISSUE TITLE
Why are you using a lexical preprocessor?

### ISSUE THREAD

**Issue by lmoellendorf** [in4lio/ev3dev-c#24]
I would like to use ev3dev to teach C programming to some kids. [ev3dev - Programming Languages](https://www.ev3dev.org/docs/programming-languages/) recommends your ev3dev-c lib.

I saw that your lib is not ready for ev3dev-stretch yet (#23). I would love to contribute, but I hesitate to learn the ropes of yupp if I do not understand why it is useful at all.

**Comment by tcwan** [comment]
I'm not the author, but I suspect it is due to the fact that the sysfs subsystem specifies I/O controls via file paths, making manual coding tedious and error prone. Since the sysfs approach has a pretty standard structure, it is better to model the devices and sensors as objects and then generate the access functions procedurally. 

The author has been rather quiet the past 6 months, so I'm in limbo as well w.r.t. Stretch support, since that is the version I intend to target for my project.

NB: I'm using evdev-c to build a core library to support teaching [ARM Assembly Language programming](https://github.com/tcwan/ev3dev-arm-bbr) on the ev3dev platform to college students. It is still very much a work in progress, and I've been on hiatus due to other work commitments. I've looked at the other [C-based libraries for EV3](https://github.com/c4ev3/EV3-API) but so far ev3dev-c is the most flexible since it runs on top of the ev3dev distribution, allowing a choice of different languages for programming.

You might also want to take a look at some [getting started docs](https://github.com/ev3dev/edu-docs) on embedded C development for ev3dev.

**Comment by in4lio** [comment]
Hi @tcwan -- thanks a lot you for your support!

Hi @lmoellendorf

**yupp** allows to generate a huge amount of C code (functions, enumerations, constants) using a number of dictionaries, which describe properties of ports, motors, and sensors. For instance, descriptions for the sensors are deriving from JSON file (http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensors.json). Thus, if the list of sensors are changed, you only need to rebuild the library.

I plan to support Stretch but haven't begun yet. The main reason is the lack of time. If you are faced with an exact list of changes in Stretch, please let me know, it will be helpful. We should take into account that -- since ev3dev Stretch still in the beta stage -- the interface can be changed significantly.

Best regards
Vitaly

**Comment by in4lio** [comment]
@dlech: Hi David, thank you for letting me know. BTW, do we have something like a list of changes for  ev3dev-stretch? Thanks again for your amazing work!

**Comment by lmoellendorf** [comment]
Hi @tcwan, @in4lio, @dlech,

thanks for your answers. It is good to see that this project is still actively maintained. 

@in4lio, I was not aware that there are JSON files describing the sensors in ev3dev. In this case it is totally reasonable to make use of those and generate the code.

For now I will downgrade to jessie and use your lib for our projects. Maybe we are able to contribute later when we became more familiar with ev3dev and ev3dev-c.

**Comment by tcwan** [comment]
@in4lio:

Someone forked ev3dev-c and made non-portable changes to the code to support ev3dev-stretch.

https://github.com/Evolitist/ev3dev-c

I think it may be a good idea to scan through the changes, which will give you some idea of what needs to be done to support stretch.
